#include "chart_render_vegalite.h"

#include "vegalite_spec.h"

#include <cairo.h>
#include <sys/stat.h>
#include <unistd.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <cmath>
#include <chrono>

// Embedded by CMakeLists.txt's `ld -r -b binary` step (see
// 3rdparty/vl-convert/README.md for why that's used instead of the hex-
// array embed_binary_resource() helper the small font binaries use --
// this binary is ~84MB, two orders of magnitude past where that helper's
// CMake-string hex encoding stays fast: confirmed live, it didn't finish
// inside 60s at this size). The wrapper symbols below are generated by
// CMakeLists.txt into a tiny companion .cpp that re-exports ld's mangled
// _binary_..._start/_end symbols under stable names.
extern const unsigned char *const vl_convert_binary;
extern const size_t vl_convert_binary_size;

namespace {

bool fileExists(const std::string &path) { struct stat st; return stat(path.c_str(), &st) == 0; }

std::string homeDir() {
    const char *h = std::getenv("HOME");
    return h ? h : "";
}

void mkdirParents(const std::string &dir) {
    std::string partial;
    for (size_t i = 1; i <= dir.size(); ++i) {
        if (i == dir.size() || dir[i] == '/') {
            partial = dir.substr(0, i);
            if (!partial.empty()) mkdir(partial.c_str(), 0755); // ignore EEXIST and other errors
        }
    }
}

std::string vlConvertSeedDir() { return homeDir() + "/.config/doublecmd/markdownview_vlconvert"; }
std::string vlConvertSeedPath() { return vlConvertSeedDir() + "/vl-convert"; }

// Writes the embedded vl-convert binary out once (mirrors the embedded
// math fonts' own self-seeding in markdown_engine.cpp).
bool seedVlConvertBinary() {
    std::string binPath = vlConvertSeedPath();
    if (fileExists(binPath)) return true; // already seeded, from this run or a previous one
    mkdirParents(vlConvertSeedDir());
    std::ofstream f(binPath, std::ios::binary | std::ios::trunc);
    if (!f) return false;
    f.write(reinterpret_cast<const char *>(vl_convert_binary), (std::streamsize)vl_convert_binary_size);
    f.close();
    if (!f) return false;
    chmod(binPath.c_str(), 0755);
    return true;
}

std::string tempFilePath(const std::string &suffix) {
    return "/tmp/markdownview_vl_" + std::to_string(::getpid()) + "_" +
           std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()) + suffix;
}

bool runVlConvert(const std::string &specPath, const std::string &outPath, double scale) {
    std::ostringstream cmd;
    cmd << "\"" << vlConvertSeedPath() << "\" vl2png --input \"" << specPath << "\" --output \"" << outPath
        << "\" --scale " << scale << " 2>/dev/null";
    int rc = std::system(cmd.str().c_str());
    return rc == 0 && fileExists(outPath);
}

// Reads width/height straight out of the PNG's IHDR chunk (bytes 16-23,
// big-endian) rather than trying to predict them from the spec:
// Vega-Lite's "width"/"height" set the PLOT rectangle, not the whole
// exported image (title, legend and axis chrome all add to it), so the
// only honest source of the final pixel size is the PNG itself.
bool readPngDimensions(const std::vector<uint8_t> &png, int &w, int &h) {
    if (png.size() < 24) return false;
    static const uint8_t sig[8] = {0x89, 'P', 'N', 'G', '\r', '\n', 0x1a, '\n'};
    for (int i = 0; i < 8; ++i) if (png[i] != sig[i]) return false;
    auto be32 = [&](size_t off) {
        return (uint32_t(png[off]) << 24) | (uint32_t(png[off + 1]) << 16) |
               (uint32_t(png[off + 2]) << 8) | uint32_t(png[off + 3]);
    };
    w = (int)be32(16);
    h = (int)be32(20);
    return w > 0 && h > 0;
}

// Smoothly downscales an oversampled PNG to its final display size before
// the caller embeds it, instead of shipping the oversampled bytes and
// leaving the downscale to whatever displays it. Qt's QTextDocument (this
// plugin's rich-text engine) does not apply smooth/antialiased scaling to
// an <img> tag's pixel data, confirmed live: a chart looked clean as a raw
// PNG but heavily aliased once actually displayed. latex_render_qt.cpp
// solves the identical problem for LaTeX renders via Qt's own
// QImage::scaled(..., SmoothTransformation); this does the equivalent with
// Cairo (toolkit-neutral, already a shared dependency here). Returns the
// original bytes unchanged on any decode failure.
struct PngReadState { const uint8_t *data; size_t size, pos; };

cairo_status_t pngReadCallback(void *closure, unsigned char *outData, unsigned int length) {
    auto *st = static_cast<PngReadState *>(closure);
    if (st->pos + length > st->size) return CAIRO_STATUS_READ_ERROR;
    memcpy(outData, st->data + st->pos, length);
    st->pos += length;
    return CAIRO_STATUS_SUCCESS;
}

cairo_status_t pngWriteCallback(void *closure, const unsigned char *data, unsigned int length) {
    auto *out = static_cast<std::vector<uint8_t> *>(closure);
    out->insert(out->end(), data, data + length);
    return CAIRO_STATUS_SUCCESS;
}

std::vector<uint8_t> smoothDownscalePng(const std::vector<uint8_t> &png, int targetW, int targetH) {
    PngReadState st{png.data(), png.size(), 0};
    cairo_surface_t *src = cairo_image_surface_create_from_png_stream(pngReadCallback, &st);
    if (cairo_surface_status(src) != CAIRO_STATUS_SUCCESS) { cairo_surface_destroy(src); return png; }
    int srcW = cairo_image_surface_get_width(src), srcH = cairo_image_surface_get_height(src);
    if (srcW <= 0 || srcH <= 0 || targetW <= 0 || targetH <= 0) { cairo_surface_destroy(src); return png; }

    cairo_surface_t *dst = cairo_image_surface_create(CAIRO_FORMAT_ARGB32, targetW, targetH);
    cairo_t *cr = cairo_create(dst);
    cairo_scale(cr, (double)targetW / srcW, (double)targetH / srcH);
    cairo_set_source_surface(cr, src, 0, 0);
    cairo_pattern_set_filter(cairo_get_source(cr), CAIRO_FILTER_BEST);
    cairo_paint(cr);
    cairo_destroy(cr);
    cairo_surface_destroy(src);

    std::vector<uint8_t> out;
    cairo_status_t writeStatus = cairo_surface_write_to_png_stream(dst, pngWriteCallback, &out);
    cairo_surface_destroy(dst);
    if (writeStatus != CAIRO_STATUS_SUCCESS || out.empty()) return png;
    return out;
}

double g_displayScale = 1.0;

} // namespace

namespace VegaLite {

void setDisplayScale(double scale) {
    // Clamped: a nonsense value here silently multiplies every render's
    // pixel budget, and vl-convert will happily try to produce it.
    if (scale > 0.5 && scale <= 4.0) g_displayScale = scale;
}

bool isCompiledIn() { return true; }

bool isAvailable() {
    static bool checked = false;
    static bool available = false;
    if (checked) return available;
    checked = true;
    if (seedVlConvertBinary() && access(vlConvertSeedPath().c_str(), X_OK) == 0) available = true;
    return available;
}

std::vector<uint8_t> renderVegaLiteSpecPng(const std::string &vegaLiteJson, bool darkMode,
                                            const std::string &bodyFontFamily,
                                            int &logicalWidth, int &logicalHeight) {
    if (!isAvailable()) return {};

    // Exactly the treatment the Kroki path applies before POSTing (see
    // DiagramRender::renderVegaLiteWeb) -- shared so both editions lay the
    // same figure out the same way.
    std::string spec = VegaLiteSpec::normalizeSpec(vegaLiteJson, darkMode, bodyFontFamily);
    if (spec.empty()) return {}; // malformed JSON -- caller leaves the fenced block as plain text

    std::string specPath = tempFilePath(".vl.json");
    std::string outPath = tempFilePath(".png");
    {
        std::ofstream f(specPath);
        if (!f) return {};
        f << spec;
    }

    // Oversample, then downscale with a real filter below -- see
    // smoothDownscalePng for why the downscale can't be left to Qt.
    constexpr double kScale = 3.0;
    bool ok = runVlConvert(specPath, outPath, kScale);
    if (!std::getenv("MARKDOWNVIEW_KEEP_VL_SPEC")) ::unlink(specPath.c_str()); // debugging aid: set to inspect the generated spec
    if (!ok) { ::unlink(outPath.c_str()); return {}; }

    std::ifstream in(outPath, std::ios::binary);
    std::vector<uint8_t> png((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
    ::unlink(outPath.c_str());
    if (png.empty()) return {};

    int pxW = 0, pxH = 0;
    if (readPngDimensions(png, pxW, pxH)) {
        logicalWidth = (int)std::lround(pxW / kScale);
        logicalHeight = (int)std::lround(pxH / kScale);
        // Rendered at the display's own pixel ratio while still DECLARED
        // at logical size by the caller, so the image maps 1:1 onto
        // device pixels instead of being stretched by the toolkit.
        png = smoothDownscalePng(png, (int)std::lround(logicalWidth * g_displayScale),
                                       (int)std::lround(logicalHeight * g_displayScale));
    }
    return png;
}

} // namespace VegaLite
